import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth.routes";
import companyRouter from "./company.routes";
import requirementsRouter from "./requirements";
import candidatesRouter from "./candidate.routes";
import jobRouter from "./job.routes";
import pipelineRouter from "./pipeline";
import pipelinesRouter from "./pipeline.routes";
import screeningRouter from "./screening";
import screeningsRouter from "./screening.routes";
import assessmentsRouter from "./assessment.routes";
import interviewsRouter from "./interview.routes";
import clientInterviewsRouter from "./client-interviews";
import offersRouter from "./offers";
import joiningRouter from "./joining";
import dashboardRouter from "./dashboard";
import notificationsRouter from "./notifications";
import uploadRouter from "./upload.routes";
import aiRouter from "./ai";
import shareRouter from "./share";
import allocationRouter from "./candidates/allocation";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/companies", companyRouter);
router.use(requirementsRouter);
router.use("/candidates", candidatesRouter);
router.use("/jobs", jobRouter);
router.use("/pipelines", pipelinesRouter);
router.use("/screenings", screeningsRouter);
router.use(pipelineRouter);
router.use(screeningRouter);
router.use("/assessments", assessmentsRouter);
router.use("/interviews", interviewsRouter);
router.use(clientInterviewsRouter);
router.use(offersRouter);
router.use(joiningRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(uploadRouter);
router.use(aiRouter);
router.use(shareRouter);
router.use(allocationRouter);

export default router;
