/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ProcessFlowRouteImport } from './routes/process-flow'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as JoiningRouteImport } from './routes/joining'
import { Route as ClientInterviewsRouteImport } from './routes/client-interviews'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentCandidateIdRouteImport } from './routes/assessment.$candidateId'
import { Route as ApiPublicDownloadCodebaseRouteImport } from './routes/api/public/download-codebase'

const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessFlowRoute = ProcessFlowRouteImport.update({
  id: '/process-flow',
  path: '/process-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const JoiningRoute = JoiningRouteImport.update({
  id: '/joining',
  path: '/joining',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientInterviewsRoute = ClientInterviewsRouteImport.update({
  id: '/client-interviews',
  path: '/client-interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentCandidateIdRoute = AssessmentCandidateIdRouteImport.update({
  id: '/assessment/$candidateId',
  path: '/assessment/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadCodebaseRoute =
  ApiPublicDownloadCodebaseRouteImport.update({
    id: '/api/public/download-codebase',
    path: '/api/public/download-codebase',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/candidates': typeof CandidatesRoute
  '/client-interviews': typeof ClientInterviewsRoute
  '/joining': typeof JoiningRoute
  '/kanban': typeof KanbanRoute
  '/offers': typeof OffersRoute
  '/process-flow': typeof ProcessFlowRoute
  '/requirements': typeof RequirementsRoute
  '/screening': typeof ScreeningRoute
  '/assessment/$candidateId': typeof AssessmentCandidateIdRoute
  '/api/public/download-codebase': typeof ApiPublicDownloadCodebaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/candidates': typeof CandidatesRoute
  '/client-interviews': typeof ClientInterviewsRoute
  '/joining': typeof JoiningRoute
  '/kanban': typeof KanbanRoute
  '/offers': typeof OffersRoute
  '/process-flow': typeof ProcessFlowRoute
  '/requirements': typeof RequirementsRoute
  '/screening': typeof ScreeningRoute
  '/assessment/$candidateId': typeof AssessmentCandidateIdRoute
  '/api/public/download-codebase': typeof ApiPublicDownloadCodebaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/candidates': typeof CandidatesRoute
  '/client-interviews': typeof ClientInterviewsRoute
  '/joining': typeof JoiningRoute
  '/kanban': typeof KanbanRoute
  '/offers': typeof OffersRoute
  '/process-flow': typeof ProcessFlowRoute
  '/requirements': typeof RequirementsRoute
  '/screening': typeof ScreeningRoute
  '/assessment/$candidateId': typeof AssessmentCandidateIdRoute
  '/api/public/download-codebase': typeof ApiPublicDownloadCodebaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/candidates'
    | '/client-interviews'
    | '/joining'
    | '/kanban'
    | '/offers'
    | '/process-flow'
    | '/requirements'
    | '/screening'
    | '/assessment/$candidateId'
    | '/api/public/download-codebase'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/candidates'
    | '/client-interviews'
    | '/joining'
    | '/kanban'
    | '/offers'
    | '/process-flow'
    | '/requirements'
    | '/screening'
    | '/assessment/$candidateId'
    | '/api/public/download-codebase'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/candidates'
    | '/client-interviews'
    | '/joining'
    | '/kanban'
    | '/offers'
    | '/process-flow'
    | '/requirements'
    | '/screening'
    | '/assessment/$candidateId'
    | '/api/public/download-codebase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  CandidatesRoute: typeof CandidatesRoute
  ClientInterviewsRoute: typeof ClientInterviewsRoute
  JoiningRoute: typeof JoiningRoute
  KanbanRoute: typeof KanbanRoute
  OffersRoute: typeof OffersRoute
  ProcessFlowRoute: typeof ProcessFlowRoute
  RequirementsRoute: typeof RequirementsRoute
  ScreeningRoute: typeof ScreeningRoute
  AssessmentCandidateIdRoute: typeof AssessmentCandidateIdRoute
  ApiPublicDownloadCodebaseRoute: typeof ApiPublicDownloadCodebaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-flow': {
      id: '/process-flow'
      path: '/process-flow'
      fullPath: '/process-flow'
      preLoaderRoute: typeof ProcessFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joining': {
      id: '/joining'
      path: '/joining'
      fullPath: '/joining'
      preLoaderRoute: typeof JoiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-interviews': {
      id: '/client-interviews'
      path: '/client-interviews'
      fullPath: '/client-interviews'
      preLoaderRoute: typeof ClientInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$candidateId': {
      id: '/assessment/$candidateId'
      path: '/assessment/$candidateId'
      fullPath: '/assessment/$candidateId'
      preLoaderRoute: typeof AssessmentCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download-codebase': {
      id: '/api/public/download-codebase'
      path: '/api/public/download-codebase'
      fullPath: '/api/public/download-codebase'
      preLoaderRoute: typeof ApiPublicDownloadCodebaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  CandidatesRoute: CandidatesRoute,
  ClientInterviewsRoute: ClientInterviewsRoute,
  JoiningRoute: JoiningRoute,
  KanbanRoute: KanbanRoute,
  OffersRoute: OffersRoute,
  ProcessFlowRoute: ProcessFlowRoute,
  RequirementsRoute: RequirementsRoute,
  ScreeningRoute: ScreeningRoute,
  AssessmentCandidateIdRoute: AssessmentCandidateIdRoute,
  ApiPublicDownloadCodebaseRoute: ApiPublicDownloadCodebaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
